name: Welcome to SWAGAZON

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the SWAGAZON contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Welcome to **SWAGAZON**!  
            Thank you for opening your first issue. Our team will review it soon.  
            Stay tuned and feel free to contribute more! 💡

          pr-message: |
            🎉 Yay! Your first pull request to **SWAGAZON**!  
            Thank you for your contribution 🚀  
            We appreciate your effort and can’t wait to review it. 💜
