E-commerce Website Frontend - YAML Config 
 
project: 
  name: E-commerce Website  
  framework: None 
  language: html, css, javascript 
  package_manager: None 
 
structure: 
  src: 
    - assets: 
        - images/ 
        - styles/ 
    - components: 
       -Html:for the structure 
       - Css:for styling
       -Javascript:for dynamic behavior
    - pages: 
        - Hindex.html
        -Login.html
         -kidssection.html
         -Mindex.html 
         - about.html
         -Dresses.html
         -Product.html 
         - cart.html 
         
    - scripts: 
-Hscript.js

    - styles: 
-Hstyle.css
-Mstyle.css

dependencies: 
  Node.js 
 
devDependencies: 
  live-Server 
 
scripts: 
  Node.js 
 
environment: 
  port: 5500  

description: > 
  This is the frontend of an E-commerce website. It allows users to browse products, add items to the cart, and proceed to checkout. Built using HTML, CSS, and JavaScript. 

